from playwright.sync_api import sync_playwright
import time

p = sync_playwright().start()
browser = p.chromium.launch(headless=False)
page = browser.new_page()
page.goto('http://127.0.0.1:5045/auth/login')
page.fill('input[name="username"]', 'admin')
page.fill('input[name="password"]', '@Xx123456789xX@')
page.click('button[type="submit"]')
page.wait_for_url('**/dashboard')
page.goto('http://127.0.0.1:5045/medicines')
page.wait_for_load_state('networkidle')
initial = page.locator('table tbody tr').count()
print(f'Initial: {initial}')
cb = page.locator('.bulk-select:not([disabled])')
sid = cb.first.get_attribute('value')
cb.first.check()
page.wait_for_selector('#bulkDeleteBtn', state='visible')
page.on('dialog', lambda d: d.accept())
page.click('#bulkDeleteBtn')
time.sleep(1)
exists = page.locator(f'tr[data-id="{sid}"]').count() > 0
print(f'Removed: {not exists}')
after = page.locator('table tbody tr').count()
print(f'After: {after}')
time.sleep(3)
final = page.locator('table tbody tr').count()
print(f'Final: {final}')
print(f'SUCCESS: {final == initial - 1}')
time.sleep(5)
browser.close()
p.stop()
